### ISSUE TITLE
CI Setup

### ISSUE THREAD

**Issue by Hounsvad** [devantler/software-engineering-f22#13]
Setup the ci to ghcr

**Comment by devantler** [comment]
@Hounsvad Jeg kiggede lige på dette. Det er ikke længere nødvendigt at oprette en Personal Access Token. Man kan benytte den autogenerede GITHUB_TOKEN til at authenticate med ghcr.io registriet - ret nice! :-D

Jeg har lagt et template ind i `.github/workflows/ghcr-template.yml` der viser hvordan :-) 

Jeg tester også lige for en god ordens skyld at det virker senere på ugen/weekenden :-)
